// THE security header policy. One file, one source of truth.
//
// Two emission paths consume it:
//   1. the emit-headers integration, which writes dist/_headers for static assets
//   2. from Phase 3 onward, server-side route handlers, which import it directly
//
// CSP is split on purpose and this is not optional:
//   - per-page script/style hashes are generated by Astro into a <meta> tag,
//     because the hashes differ per page and cannot live in a static file
//   - frame-ancestors is ignored by browsers inside a <meta> tag, so it must
//     be sent as a real HTTP header — that is what lives here
export type HeaderPair = readonly [name: string, value: string];

const PERMISSIONS_POLICY = [
  "accelerometer=()",
  "camera=()",
  "geolocation=()",
  "gyroscope=()",
  "magnetometer=()",
  "microphone=()",
  "payment=()",
  "usb=()",
  "interest-cohort=()",
].join(", ");

export function securityHeaders(isDev: boolean): HeaderPair[] {
  const headers: HeaderPair[] = [
    ["X-Content-Type-Options", "nosniff"],
    ["Referrer-Policy", "strict-origin-when-cross-origin"],
    ["Permissions-Policy", PERMISSIONS_POLICY],
    ["Content-Security-Policy", "frame-ancestors 'none'"],
  ];

  if (isDev) {
    headers.push(["X-Robots-Tag", "noindex, nofollow"]);
  }

  return headers;
}

// Astro puts a content hash in every filename under /_astro/, so the bytes
// behind one of those URLs can never change: a new build writes a new name.
// Without this the asset layer serves them `max-age=0, must-revalidate`, the
// same policy the HTML gets, and every repeat visitor pays a round trip to be
// told the stylesheet they already hold is still current.
//
// The document must NOT get this. Its URL carries no hash, so `immutable`
// there would pin a reader to a page that has moved on, with no way to
// invalidate short of changing the URL.
const HASHED_ASSET_PATH = "/_astro/*";
const IMMUTABLE = "public, max-age=31536000, immutable";

export function buildHeadersFile(isDev: boolean): string {
  const lines = ["/*"];
  for (const [name, value] of securityHeaders(isDev)) {
    lines.push(`  ${name}: ${value}`);
  }
  lines.push("", HASHED_ASSET_PATH, `  Cache-Control: ${IMMUTABLE}`);
  return lines.join("\n") + "\n";
}
